services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules: {}
