allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - sharp

overrides:
  'minimatch@<3.1.4': '3.1.4'
  'minimatch@>=9.0.0 <9.0.7': '9.0.7'
  'flatted@<3.4.2': '3.4.2'
  'picomatch@<2.3.2': '2.3.2'
  'picomatch@>=4.0.0 <4.0.4': '4.0.4'
  'js-yaml@>=4.0.0 <4.1.1': '4.1.1'
  'ajv@<6.14.0': '6.14.0'
  'brace-expansion@<1.1.13': '1.1.13'
  'brace-expansion@>=2.0.0 <2.0.3': '2.0.3'
  'defu@<6.1.5': '6.1.5'
  devalue: '^5.8.1'
